<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MDerbala" failures="1" tests="2" name="Test" time="67.779" errors="0" timestamp="2025-01-21T15:16:25 EET">
  <testcase classname="Tests.Remittances_AddNewRemittancetest" name="userCanAddNewRemittanceSuccessfully" time="44.608"/>
  <testcase classname="Tests.Remittances_TheEndDayReportofExportedRemittancesDisplayTheCorrectDataTest" name="dataIsDisplayedCorrectlyInTheEndDayReportofExportedRemittances" time="12.853">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 0 out of bounds for length 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at Tests.Remittances_TheEndDayReportofExportedRemittancesDisplayTheCorrectDataTest.compareTransactionData(Remittances_TheEndDayReportofExportedRemittancesDisplayTheCorrectDataTest.java:159)
at Tests.Remittances_TheEndDayReportofExportedRemittancesDisplayTheCorrectDataTest.validateReportData(Remittances_TheEndDayReportofExportedRemittancesDisplayTheCorrectDataTest.java:123)
at Tests.Remittances_TheEndDayReportofExportedRemittancesDisplayTheCorrectDataTest.dataIsDisplayedCorrectlyInTheEndDayReportofExportedRemittances(Remittances_TheEndDayReportofExportedRemittancesDisplayTheCorrectDataTest.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- dataIsDisplayedCorrectlyInTheEndDayReportofExportedRemittances -->
</testsuite> <!-- Test -->
