{"uuid":"36875031-bf7b-4d10-8d24-3b87a008958b","historyId":"7754b067079c5fa63a1a12dc7485cdeb","fullName":"Tests.Remittances_TheEndDayReportofExportedRemittancesDisplayTheCorrectDataTest.dataIsDisplayedCorrectlyInTheEndDayReportofExportedRemittances","labels":[{"name":"package","value":"Tests.Remittances_TheEndDayReportofExportedRemittancesDisplayTheCorrectDataTest"},{"name":"testClass","value":"Tests.Remittances_TheEndDayReportofExportedRemittancesDisplayTheCorrectDataTest"},{"name":"testMethod","value":"dataIsDisplayedCorrectlyInTheEndDayReportofExportedRemittances"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"Tests.Remittances_TheEndDayReportofExportedRemittancesDisplayTheCorrectDataTest"},{"name":"host","value":"MDerbala"},{"name":"thread","value":"9540@MDerbala.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"dataIsDisplayedCorrectlyInTheEndDayReportofExportedRemittances","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Transaction counts do not match! expected [3] but found [2]","trace":"java.lang.AssertionError: Transaction counts do not match! expected [3] but found [2]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\r\n\tat org.testng.Assert.assertEquals(Assert.java:132)\r\n\tat org.testng.Assert.assertEquals(Assert.java:1419)\r\n\tat org.testng.Assert.assertEquals(Assert.java:1383)\r\n\tat Tests.Remittances_TheEndDayReportofExportedRemittancesDisplayTheCorrectDataTest.dataIsDisplayedCorrectlyInTheEndDayReportofExportedRemittances(Remittances_TheEndDayReportofExportedRemittancesDisplayTheCorrectDataTest.java:111)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:848)\r\n\tat org.testng.TestRunner.run(TestRunner.java:621)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1114)\r\n\tat org.testng.TestNG.run(TestNG.java:1082)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1736162406870,"stop":1736162418998}